Fix webpack error
```
$ be rake assets:precompile
yarn install v1.22.22
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.11s.
Warning: you are using an unstable release of Node.js (v23.7.0). If you encounter issues with Node.js, consider switching to an Active LTS release. More info: https://docs.npmjs.com/try-the-latest-stable-version-of-node
Compiling...
Compilation failed:
/Users/rschneeman/.gem/ruby/3.3.7/gems/activesupport-6.1.7.21/lib/active_support/logger_thread_safe_level.rb:16:in `<module:LoggerThreadSafeLevel>': uninitialized constant ActiveSupport::LoggerThreadSafeLevel::Logger (NameError)

    Logger::Severity.constants.each do |severity|
    ^^^^^^
	from /Users/rschneeman/.gem/ruby/3.3.7/gems/activesupport-6.1.7.21/lib/active_support/logger_thread_safe_level.rb:9:in `<module:ActiveSupport>'
	from /Users/rschneeman/.gem/ruby/3.3.7/gems/activesupport-6.1.7.21/lib/active_support/logger_thread_safe_level.rb:8:in `<top (required)>'
	from /Users/rschneeman/.rubies/ruby-3.3.7/lib/ruby/3.3.0/bundled_gems.rb:69:in `require'
	from /Users/rschneeman/.rubies/ruby-3.3.7/lib/ruby/3.3.0/bundled_gems.rb:69:in `block (2 levels) in replace_require'
	from /Users/rschneeman/.gem/ruby/3.3.7/gems/activesupport-6.1.7.21/lib/active_support/logger_silence.rb:5:in `<top (required)>'
	from /Users/rschneeman/.rubies/ruby-3.3.7/lib/ruby/3.3.0/bundled_gems.rb:69:in `require'
	from /Users/rschneeman/.rubies/ruby-3.3.7/lib/ruby/3.3.0/bundled_gems.rb:69:in `block (2 levels) in replace_require'
	from /Users/rschneeman/.gem/ruby/3.3.7/gems/activesupport-6.1.7.21/lib/active_support/logger.rb:3:in `<top (required)>'
	from /Users/rschneeman/.rubies/ruby-3.3.7/lib/ruby/3.3.0/bundled_gems.rb:69:in `require'
	from /Users/rschneeman/.rubies/ruby-3.3.7/lib/ruby/3.3.0/bundled_gems.rb:69:in `block (2 levels) in replace_require'
	from /Users/rschneeman/.gem/ruby/3.3.7/gems/webpacker-5.4.4/lib/webpacker.rb:3:in `<top (required)>'
	from /Users/rschneeman/.rubies/ruby-3.3.7/lib/ruby/3.3.0/bundled_gems.rb:69:in `require'
	from /Users/rschneeman/.rubies/ruby-3.3.7/lib/ruby/3.3.0/bundled_gems.rb:69:in `block (2 levels) in replace_require'
	from ./bin/webpack:12:in `<main>'
```